name: dbt CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-postgres

    - name: Set up dbt profile
      run: |
        mkdir -p ~/.dbt
        echo "${{ secrets.DBT_PROFILES_YML }}" > ~/.dbt/profiles.yml

    - name: Run dbt
      run: |
        dbt deps
        dbt seed
        dbt run
        dbt test
